import $ from 'jquery';
import './scss/style.scss';
import './blocks/dropdown/dropdown';
import './blocks/calendar/calendar';
import './blocks/date-dropdown/date-dropdown';
import './blocks/range-slider/range-slider';
import './blocks/dropdown-interior/dropdown-interior';
import './blocks/satisfaction-chart/satisfaction-chart';
import './blocks/button-like/button-like';
import './blocks/review/review';
import './blocks/card-room/card-room';
import './blocks/expandable-checkbox-list/expandable-checkbox-list';
import './blocks/card-confirmation/card-confirmation';